version: '3.8'

services:
  twitter-automation:
    build: .
    container_name: twitter-automation
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    mem_limit: 2g
    cpu_percent: 50
    
    # Optional: Use external proxy network
    networks:
      - proxy-network
    
    # Health monitoring
    healthcheck:
      test: ["CMD", "node", "-e", "console.log(\'OK\')"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Optional: Redis for advanced state management
  redis:
    image: redis:7-alpine
    container_name: twitter-redis
    restart: unless-stopped
    volumes:
      - redis-data:/data
    networks:
      - proxy-network

volumes:
  redis-data:

networks:
  proxy-network:
    external: true

